name: pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: .
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - run: npm install ; rm .gitignore
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          force_orphan: true
          publish_dir: .
          publish_branch: gh-pages
